spring:
  profiles:
    active: prod

  thymeleaf:
    cache: true  # 프로덕션 환경에서는 캐시를 활성화합니다.

  application:
    name: demo

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate  # 프로덕션에서는 스키마를 자동으로 생성하지 않도록 합니다.
    properties:
      hibernate:
        format_sql: false  # 프로덕션에서는 SQL 포맷팅을 비활성화합니다.
        use_sql_comments: false  # 프로덕션에서는 SQL 주석을 비활성화합니다.
        show_sql: false  # 프로덕션에서는 SQL 출력을 비활성화합니다.

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  error:
    whitelabel:
      enabled: false

